global using AircraftMaintenanceOperations.Application.Common.Interfaces;
global using AircraftMaintenanceOperations.Application.Features.User.Commands.ChangeUserRole;
global using AircraftMaintenanceOperations.Domain.Entities;
global using AircraftMaintenanceOperations.Domain.Enums;
global using AircraftMaintenanceOperations.Infrastructure.Persistence.Context;
global using Microsoft.EntityFrameworkCore;