namespace AircraftMaintenanceOperations.Application.Features.InventoryTransaction.Queries.GetInventoryTransactions;

public record GetInventoryTransactionsQuery(Guid InventoryPartId) : IQuery<GetInventoryTransactionsQueryResult>;
public record GetInventoryTransactionsQueryResult(IEnumerable<InventoryTransactionDto> InventoryTransactions);